export const tokenAbi = [
	{ type: "error", inputs: [], name: "InvalidInitialization" },
	{ type: "error", inputs: [], name: "NotInitializing" },
	{
		type: "error",
		inputs: [{ name: "owner", internalType: "address", type: "address" }],
		name: "OwnableInvalidOwner",
	},
	{
		type: "error",
		inputs: [{ name: "account", internalType: "address", type: "address" }],
		name: "OwnableUnauthorizedAccount",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_userAddress",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{ name: "_isFrozen", internalType: "bool", type: "bool", indexed: true },
			{
				name: "_owner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "AddressFrozen",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_agent",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "AgentAdded",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_agent",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "AgentRemoved",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "owner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "spender",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "value",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "Approval",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_compliance",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "ComplianceAdded",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_identityRegistry",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "IdentityRegistryAdded",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "version",
				internalType: "uint64",
				type: "uint64",
				indexed: false,
			},
		],
		name: "Initialized",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "previousOwner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "newOwner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "OwnershipTransferred",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_userAddress",
				internalType: "address",
				type: "address",
				indexed: false,
			},
		],
		name: "Paused",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_lostWallet",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "_newWallet",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "_investorOnchainID",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "RecoverySuccess",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_userAddress",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "_amount",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "TokensFrozen",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_userAddress",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "_amount",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "TokensUnfrozen",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{ name: "from", internalType: "address", type: "address", indexed: true },
			{ name: "to", internalType: "address", type: "address", indexed: true },
			{
				name: "value",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "Transfer",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_userAddress",
				internalType: "address",
				type: "address",
				indexed: false,
			},
		],
		name: "Unpaused",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "_newName",
				internalType: "string",
				type: "string",
				indexed: true,
			},
			{
				name: "_newSymbol",
				internalType: "string",
				type: "string",
				indexed: true,
			},
			{
				name: "_newDecimals",
				internalType: "uint8",
				type: "uint8",
				indexed: false,
			},
			{
				name: "_newVersion",
				internalType: "string",
				type: "string",
				indexed: false,
			},
			{
				name: "_newOnchainID",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "UpdatedTokenInformation",
	},
	{
		type: "function",
		inputs: [{ name: "_agent", internalType: "address", type: "address" }],
		name: "addAgent",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_owner", internalType: "address", type: "address" },
			{ name: "_spender", internalType: "address", type: "address" },
		],
		name: "allowance",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_spender", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "approve",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
		],
		name: "balanceOf",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddresses", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "batchBurn",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_fromList", internalType: "address[]", type: "address[]" },
			{ name: "_toList", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "batchForcedTransfer",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddresses", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "batchFreezePartialTokens",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_toList", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "batchMint",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddresses", internalType: "address[]", type: "address[]" },
			{ name: "_freeze", internalType: "bool[]", type: "bool[]" },
		],
		name: "batchSetAddressFrozen",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_toList", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "batchTransfer",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddresses", internalType: "address[]", type: "address[]" },
			{ name: "_amounts", internalType: "uint256[]", type: "uint256[]" },
		],
		name: "batchUnfreezePartialTokens",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "burn",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "compliance",
		outputs: [
			{
				name: "",
				internalType: "contract IModularCompliance",
				type: "address",
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "decimals",
		outputs: [{ name: "", internalType: "uint8", type: "uint8" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_spender", internalType: "address", type: "address" },
			{ name: "_subtractedValue", internalType: "uint256", type: "uint256" },
		],
		name: "decreaseAllowance",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_from", internalType: "address", type: "address" },
			{ name: "_to", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "forcedTransfer",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "freezePartialTokens",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
		],
		name: "getFrozenTokens",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "identityRegistry",
		outputs: [
			{ name: "", internalType: "contract IIdentityRegistry", type: "address" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_spender", internalType: "address", type: "address" },
			{ name: "_addedValue", internalType: "uint256", type: "uint256" },
		],
		name: "increaseAllowance",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_identityRegistry", internalType: "address", type: "address" },
			{ name: "_compliance", internalType: "address", type: "address" },
			{ name: "_name", internalType: "string", type: "string" },
			{ name: "_symbol", internalType: "string", type: "string" },
			{ name: "_decimals", internalType: "uint8", type: "uint8" },
			{ name: "_onchainID", internalType: "address", type: "address" },
		],
		name: "init",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_agent", internalType: "address", type: "address" }],
		name: "isAgent",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
		],
		name: "isFrozen",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_to", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "mint",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "name",
		outputs: [{ name: "", internalType: "string", type: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "onchainID",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "owner",
		outputs: [{ name: "", internalType: "address", type: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "pause",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "paused",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_lostWallet", internalType: "address", type: "address" },
			{ name: "_newWallet", internalType: "address", type: "address" },
			{ name: "_investorOnchainID", internalType: "address", type: "address" },
		],
		name: "recoveryAddress",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_agent", internalType: "address", type: "address" }],
		name: "removeAgent",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
			{ name: "_freeze", internalType: "bool", type: "bool" },
		],
		name: "setAddressFrozen",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_compliance", internalType: "address", type: "address" }],
		name: "setCompliance",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_identityRegistry", internalType: "address", type: "address" },
		],
		name: "setIdentityRegistry",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_name", internalType: "string", type: "string" }],
		name: "setName",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_onchainID", internalType: "address", type: "address" }],
		name: "setOnchainID",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "_symbol", internalType: "string", type: "string" }],
		name: "setSymbol",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "symbol",
		outputs: [{ name: "", internalType: "string", type: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [],
		name: "totalSupply",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		inputs: [
			{ name: "_to", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "transfer",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_from", internalType: "address", type: "address" },
			{ name: "_to", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "transferFrom",
		outputs: [{ name: "", internalType: "bool", type: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [
			{ name: "_userAddress", internalType: "address", type: "address" },
			{ name: "_amount", internalType: "uint256", type: "uint256" },
		],
		name: "unfreezePartialTokens",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "unpause",
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		inputs: [],
		name: "version",
		outputs: [{ name: "", internalType: "string", type: "string" }],
		stateMutability: "pure",
	},
] as const;
