import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import type React from "react";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "@fortawesome/fontawesome-free/css/brands.css";
import { Providers } from "@/app/providers";
import { Footer } from "@/components/Footers/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import { PageContent } from "@/components/Page/PageContent";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "BRU",
	description: "Generated by hand",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactElement;
}>) {
	return (
	  <html lang="en">
		<head>
		  <link rel="icon" href="/favicon.ico" sizes="any" />
		  <link
			rel="apple-touch-icon"
			href="/favicon/apple-touch-icon.png"
			type="image/png"
			sizes="180x180"
		  />
		  <title>Buildings 'R' Us</title>
		</head>
		<body
		  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
		  <Providers>
			<div
				className="min-h-screen flex justify-center"
				style={{
					backgroundColor: "#F9F3F8",
					padding: "10px 12px",
				}}
			>
				<div className="max-w-7xl w-full bg-white rounded-xl">
					<Navbar linksForPage="regularUser">
						<>
							<PageContent>{children}</PageContent>
						</>
					</Navbar>
					<div className="mt-20">
						<Footer />
					</div>
				</div>
			</div>
		  </Providers>
		</body>
	  </html>
	);
}
