import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import type React from "react";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "@fortawesome/fontawesome-free/css/brands.css";
import { Providers } from "@/app/providers";
import { Footer } from "@/components/Footers/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "BRU",
   description: "Generated by hand",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactElement;
}>) {
   return (
      <html lang="en" data-theme="light">
         <head>
            <link rel="icon" href="/favicon.ico" sizes="any" />
            <link
               rel="apple-touch-icon"
               href="/favicon/apple-touch-icon.png"
               type="image/png"
               sizes="180x180"
            />
            <title>Buildings 'R' Us</title>
         </head>
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100 text-neutral`}
         >
            <Providers>
               <Toaster richColors />
               <div className="min-h-screen flex flex-col">
                  <Navbar />
                  <main className="bg-base-100 w-full flex-1" style={{ minHeight: "50vh" }}>
                     {children}
                  </main>
                  <Footer />
               </div>
            </Providers>
         </body>
      </html>
   );
}
